version: '3.8'
services:
  postgres:
    container_name: container-pg2
    image: postgres:16.2
    hostname: localhost
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: cu_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: root
    networks:
      - keycloak_network

  keycloak:
    image: quay.io/keycloak/keycloak:23.0.6
    command: start
    environment:
      KC_HOSTNAME: localhost
      KC_HOSTNAME_PORT: 8080
      KC_HOSTNAME_STRICT_BACKCHANNEL: false
      KC_HTTP_ENABLED: true
      KC_HOSTNAME_STRICT_HTTPS: false
      KC_HEALTH_ENABLED: true
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: password
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://container-pg2:5432/cu_db
      KC_DB_USERNAME: admin
      KC_DB_PASSWORD: root
    ports:
      - 8080:8080
    restart: always
    depends_on:
      - postgres
    networks:
      - keycloak_network
    volumes:
      - ./create-user.sh:/opt/keycloak/create-user.sh
    entrypoint: ["/bin/sh", "-c", "/opt/keycloak/bin/kc.sh start & sleep 17 && /bin/sh /opt/keycloak/create-user.sh && wait"]
volumes:
  postgres_data:
    driver: local

networks:
  keycloak_network:
    driver: bridge

