spring:
  application:
      name: ResourceServer
  security:
    oauth2:
      resourceserver:
        jwt.issuer-uri: http://localhost:8080/realms/hadilka
        jwt.jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs

logging:
    level:
      org.springframework.security: TRACE
      org.springframework.boot.context.config: DEBUG

server:
  port: 8081

jwt:
  auth:
    converter:
      resource-id: greeting
      principle-attribute: preferred_username

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true