spring:
  main:
    web-application-type: reactive

  application:
    name: bff-server

  security:
    oauth2:
      client:
        registration:
          bff:
            provider: keycloak
            client-id: bff_cl
            client-secret: CLIENT_SECRET
            authorization-grant-type: authorization_code
            #              redirect-uri: http://localhost:8082/login/oauth2/code/demo
            scope: openid, profile, email, roles
        provider:
          keycloak:
            issuer-uri: http://localhost:8080/realms/hadilka

logging:
  level:
    root: INFO
    org:
      springframework:
        security: TRACE
        cloud:
          gateway: Trace
      springframework.web: DEBUG
    reactor.netty.http.server: DEBUG
server:
  port: 8082

eureka:
  client:
    serviceUrl:
      defaultZone: http://user:password@localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true
  instance:
    preferIpAddress: true

#  cloud:
#    gateway:
#      routes:
#        - id: ResourceServer
#          uri: http://localhost:8083
#          predicates:
#            - Path=/api/**




